# Generated by Django 3.1.5 on 2021-02-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_app', '0002_auto_20210205_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='width',
            field=models.PositiveIntegerField(verbose_name='Ширина'),
        ),
    ]
